Feature/xhr retry logic
OneNoteDev/WebClipper pull request #194
Opened 2016-11-10 17:35 UTC by leakymemory

This adds default retry logic to our XHRs.

2016-11-10 18:12 UTC, mttwc requested changes

2016-11-10 18:12 UTC, mttwc commented on src/tests/extensions/authenticationHelper_tests.ts
> +let savedSetTimeout;
These aren't being used

2016-11-10 18:12 UTC, mttwc commented on src/tests/helperFunctions.ts
> +	export function mockSetTimout() {
Nice!

2016-11-10 18:12 UTC, mttwc commented on src/tests/extensions/authenticationHelper_tests.ts
> +import { AuthenticationHelper } from "../../scripts/extensions/authenticationHelper";
Braces should not have spaces

2016-11-10 18:12 UTC, mttwc commented on src/tests/promiseUtils_tests.ts
> +	});
Please add some tests that use fakeTimer to test the timeout logic. For this you will want to create a new module where you don't mock out setTimeout.

2016-11-10 18:12 UTC, mttwc commented on src/scripts/promiseUtils.ts
> +					}, Math.round(Math.random() * (retryOptions.maxTimeout - retryOptions.minTimeout)) + retryOptions.minTimeout);
Is there a reason why we use a random multiplier?

2016-11-10 18:12 UTC, mttwc commented on src/tests/promiseUtils_tests.ts
> +		strictEqual(callCount, 50, "execWithRetry should call the function 500 times");
Oops, I forgot to update the assert message from 500 -> 50

2016-11-10 18:13 UTC, mttwc commented
Looking forward to using the setTimeout mocking in my saveToOneNote tests. Right now, it's using the real setTimeout and it's causing our tests to run longer. I wonder if there's other places in our codebase that can benefit from this.

2016-11-10 21:39 UTC, leakymemory commented on src/tests/extensions/authenticationHelper_tests.ts
> +import { AuthenticationHelper } from "../../scripts/extensions/authenticationHelper";
I'll remove them.  VSCode started doing it automatically for some reason.  I'll try to turn it off.

2016-11-10 21:49 UTC, mttwc commented on src/tests/extensions/authenticationHelper_tests.ts
> +import { AuthenticationHelper } from "../../scripts/extensions/authenticationHelper";
Yeah I'm having that issue too and couldn't find the setting! If you find it let me know :)

2016-11-11 17:10 UTC, mttwc commented on src/tests/promiseUtils_tests.ts
> +	});
We decided that this will be low prio as we're pretty confident that the timeouts work the way they should.

2016-11-11 17:55 UTC, mttwc commented on src/scripts/promiseUtils.ts
> +					}, Math.round(Math.random() * (retryOptions.maxTimeout - retryOptions.minTimeout)) + retryOptions.minTimeout);
As discussed :)

2016-11-11 17:55 UTC, mttwc approved these changes

2016-11-11 18:14 UTC, merged