Cleaned up promises to use established patterns
OneNoteDev/WebClipper pull request #197
Opened 2016-11-11 23:04 UTC by mttwc

Fixes #144 

@VishaalK I'll need your expert eyes on this one :P

2016-11-11 23:54 UTC, VishaalK requested changes
Had some minor comments. Looks dope!

2016-11-11 23:54 UTC, VishaalK commented on src/scripts/clipperUI/components/sectionPicker.tsx
> +		return SectionPickerClass.dataSource.getNotebooks(headers).catch((failure: OneNoteApi.RequestError) => {
The `catch` is unnecessary here. Returning the promise will propagate the error already.

2016-11-11 23:54 UTC, VishaalK commented on src/scripts/clipperUI/components/sectionPicker.tsx
> +		return SectionPickerClass.dataSource.getNotebooks(headers).catch((failure: OneNoteApi.RequestError) => {
`sectionPicker.tsx` has the error handler its in `.then()` to use the error that is returned

2016-11-11 23:54 UTC, VishaalK commented on src/scripts/saveToOneNote/oneNoteSaveablePdf.ts
> +		return this.pdf.getPageListAsDataUrls(this.buckets[index]).then((dataUrls) => {
I think you can do this here:

`return this.pdf.getPageListAsDataUrls(this.buckets[index]).then(this.createPatchRequestBody);`

It's debatable whether or not this is more readable though.

2016-11-11 23:54 UTC, VishaalK commented on src/scripts/localization/localizationHelper.ts
> +		}).catch((error) => {
I think this `catch` is also unnecessary

2016-11-11 23:54 UTC, VishaalK commented on src/scripts/http/cachedHttp.ts
> +		return getRemoteValue().then((responsePackage) => {
As a side note, why does `getRemoteValue()` not take any arguments?

2016-11-11 23:54 UTC, VishaalK commented on src/scripts/contentCapture/augmentationHelper.ts
> +				return Promise.reject(error);
This `catch` is unnecessary

2016-11-11 23:54 UTC, VishaalK commented on src/scripts/contentCapture/bookmarkHelper.ts
> +			return Promise.resolve(result);
Is this all one method? The promise stuff looks fine though

2016-11-11 23:54 UTC, VishaalK commented on src/scripts/extensions/extensionBase.ts
> +			return Promise.reject(error);
Unnecessary `catch`.

2016-11-14 18:33 UTC, mttwc commented on src/scripts/saveToOneNote/oneNoteSaveablePdf.ts
> +		return this.pdf.getPageListAsDataUrls(this.buckets[index]).then((dataUrls) => {
Interesting! I kinda like this syntax. It's succinct.

2016-11-14 18:35 UTC, mttwc commented on src/scripts/http/cachedHttp.ts
> +		return getRemoteValue().then((responsePackage) => {
getRemoteValue is passed in as a parameter and defines how the remove value should be gotten.

2016-11-14 18:36 UTC, mttwc commented on src/scripts/contentCapture/bookmarkHelper.ts
> +			return Promise.resolve(result);
Yep it is. It's pretty big so I'm sure we can refactor.

2016-11-14 19:03 UTC, mttwc commented on src/scripts/clipperUI/components/sectionPicker.tsx
> +		return SectionPickerClass.dataSource.getNotebooks(headers).catch((failure: OneNoteApi.RequestError) => {
Resolved

2016-11-14 19:03 UTC, mttwc commented on src/scripts/localization/localizationHelper.ts
> +		}).catch((error) => {
Resolved

2016-11-14 19:03 UTC, mttwc commented on src/scripts/contentCapture/augmentationHelper.ts
> +				return Promise.reject(error);
Resolved

2016-11-14 19:03 UTC, mttwc commented on src/scripts/extensions/extensionBase.ts
> +			return Promise.reject(error);
Resolved

2016-11-14 19:04 UTC, mttwc commented
@VishaalK I just pushed up another commit if you want to review that.

2016-11-14 19:04 UTC, VishaalK approved these changes

2016-11-14 19:04 UTC, merged