Fix tab index for pdf options
OneNoteDev/WebClipper pull request #399
Opened 2018-05-29 20:06 UTC by JaneHazen

2018-05-29 20:12 UTC, mttwc commented
Nice! Let's check with PM to see if the new navigation order (i.e., navigating to and from the Less button) is suitable

2018-06-01 15:46 UTC, mttwc requested changes

2018-06-01 15:46 UTC, mttwc commented on src/scripts/clipperUI/components/previewViewer/previewViewerHeaderComponentBase.tsx
> +export abstract class ButtonGroupingsComponentBase<T, P> extends ComponentBase<T, P> {
Why was this renamed?

2018-06-01 15:46 UTC, mttwc commented on src/scripts/clipperUI/components/previewViewer/previewViewerHeaderComponentBase.tsx
> +			let currentButtonGroup = buttonGroups[i];
This change was in the other PR as well. Please try and minimize overlap between branches.

2018-06-01 15:46 UTC, mttwc commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButton.tsx
> +class PdfPageSelectionRadioButton extends ButtonGroupingsComponentBase<{}, ClipperStateProp> {
Why would this extend the previously-named header class?

2018-06-01 21:22 UTC, mttwc requested changes

2018-06-01 21:22 UTC, mttwc commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButton.tsx
> +			);
nit: Indentation

2018-06-01 21:22 UTC, mttwc commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButton.tsx
> +		let selectedTabIndex = 60;
The value `60` is duplicated below. Move this to the class level.

2018-06-01 21:22 UTC, mttwc commented on src/tests/clipperUI/components/pdfClipOptions_tests.tsx
>  		test("The tab order should flow linearly between pdf options", () => {
Update test description

2018-06-01 21:22 UTC, mttwc commented on src/tests/clipperUI/mainController_tests.tsx
>  			let controllerInstance = MithrilUtils.mountToFixture(this.defaultComponent);
Update test description

2018-06-01 21:22 UTC, mttwc commented on src/tests/clipperUI/components/pdfClipOptions_tests.tsx
> +			Assert.tabOrderIsIncremental([Constants.Ids.radioPageRangeLabel, Constants.Ids.checkboxToDistributePages, Constants.Ids.checkboxToAttachPdf
nit: style

2018-06-01 21:22 UTC, mttwc commented on src/tests/clipperUI/mainController_tests.tsx
> -				controllerInstance.state.currentPanel = PanelType.ClipOptions;
Why was this line removed?

2018-06-01 21:31 UTC, JaneHazen commented on src/tests/clipperUI/components/pdfClipOptions_tests.tsx
> +			Assert.tabOrderIsIncremental([Constants.Ids.radioPageRangeLabel, Constants.Ids.checkboxToDistributePages, Constants.Ids.checkboxToAttachPdf
?

2018-06-01 21:41 UTC, mttwc approved these changes

2018-06-01 21:41 UTC, mttwc commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButton.tsx
> +			);
nit: indentation

2018-06-01 21:49 UTC, mttwc approved these changes

2018-06-01 22:03 UTC, merged