Tabbing bugs
OneNoteDev/WebClipper pull request #404
Opened 2018-06-04 17:59 UTC by JaneHazen

2018-06-04 18:25 UTC, mttwc requested changes

2018-06-04 18:25 UTC, mttwc commented on src/scripts/clipperUI/clipper.tsx
> +						if (!lowestTabIndexElement || tabbable.tabIndex < lowestTabIndexElement.tabIndex && tabbable.tabIndex > 0) {
1) Add additional braces since it's dangerous to mix || and && in the same statement without explicitly stating in which order they are evaluated
2)  Why tabIndex > 0 and not >= 0?

2018-06-04 18:25 UTC, mttwc commented on src/scripts/clipperUI/components/modeButtonSelector.tsx
> +			<div aria-live="assertive" aria-relevant="text" className={Constants.Classes.srOnly}>{stringToTellUserModeHasChanged}</div>
What does the narrator do here?

2018-06-04 18:25 UTC, mttwc commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButtonBase.tsx
> +export abstract class pdfPageSelectionRadioButtonBase<T, P> extends ComponentBase<T, P> {
Naming convention (capital first letter)

2018-06-04 18:25 UTC, mttwc commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButtonBase.tsx
> +export abstract class pdfPageSelectionRadioButtonBase<T, P> extends ComponentBase<T, P> {
Is <T, P> needed? Can we use export abstract class pdfPageSelectionRadioButtonBase extends ComponentBase?

2018-06-04 18:25 UTC, mttwc commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButtonBase.tsx
> +export abstract class pdfPageSelectionRadioButtonBase<T, P> extends ComponentBase<T, P> {
Why is this separated into its own abstract class?

2018-06-04 18:25 UTC, mttwc commented on src/scripts/clipperUI/panels/regionSelectingPanel.tsx
> +						<div className={Constants.Classes.srOnly} role="alert">
What does the narrator do here?

2018-06-04 18:34 UTC, JaneHazen commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButtonBase.tsx
> +export abstract class pdfPageSelectionRadioButtonBase<T, P> extends ComponentBase<T, P> {
The ComponentBase requires them

2018-06-05 21:54 UTC, mttwc approved these changes

2018-06-05 21:54 UTC, mttwc commented on src/scripts/clipperUI/components/pdfPageSelectionRadioButton.tsx
> +export interface radioButtonGroup {
Naming convention

2018-06-05 22:02 UTC, merged